### ISSUE TITLE
Create Location Groups for various locations

### ISSUE THREAD

**Issue by cjmang** [cjmang/Archipelago#12]
### What feature would you like to see?

Would be nice to have location groups for e.g. superbosses, and maybe some of the regions (who wants to ascend air's rock?)

**Comment by Dragion147** [comment]
List of dungeons / groups
Shrine of the sea god
Kandorean Temple
Dehkan Plateau
Madra Catacombs
Yampi Desert
Yampi Desert Cave
Air's Rock
Taopo Swamp
Gabomba Statue
Gabomba Catacombs (maybe merge with statue ?)
Ankohl Ruins
Gaia Rock
Izumo Shrine
Treasure Isle
Tundaria Tower
Aqua Rock
Jupiter Lighthouse
Magma Rock
Mars Lighthouse Front
Mars Lighthouse Back (after teleport)
Anemos Sanctum
Turtle Island

**Comment by Dragion147** [comment]
Lots of location groups added with https://github.com/cjmang/Archipelago/commit/f839812f1836b4a26316231a7c3b02052f87dd9a
